### ISSUE TITLE
EACCES: permission denied copyfile product.json to product.json.orig

### ISSUE THREAD

**Issue by sjsepan3** [jameslan/openvsx-vscode#1]
I get this error switching to 'open-vsx.org Marketplace' in both codium and code.

"Failed to update marketplace configuration: Error: EACCES: permission denied, copyfile '/usr/share/codium/resources/app/product.json' -> '/usr/share/codium/resources/app/product.json.orig'"

"Failed to update marketplace configuration: Error: EACCES: permission denied, copyfile '/usr/share/code/resources/app/product.json' -> '/usr/share/code/resources/app/product.json.orig'"

settings:
`	"openvsx.switcher.marketplaces": [],
`

System Info:
Linux Mint 21 Cinnamon

System:
  Kernel: 5.15.0-72-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.8
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: Dell product: OptiPlex 7020 v: 00 serial: <superuser required> Chassis:
    type: 6 serial: <superuser required>
  Mobo: Dell model: 0F5C5X v: A00 serial: <superuser required> BIOS: Dell v: A10
    date: 09/22/2016
Battery:
  Device-1: hidpp_battery_0 model: Logitech M570 serial: <filter> charge: 40% status: Discharging
CPU:
  Info: quad core model: Intel Core i5-4590 bits: 64 type: MCP arch: Haswell rev: 3 cache:
    L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 3291 high: 3293 min/max: 800/3700 cores: 1: 3293 2: 3290 3: 3289 4: 3293
    bogomips: 26340
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: AMD Oland [Radeon HD 8570 / R5 430 OEM R7 240/340 Radeon 520 OEM] vendor: Dell
    driver: radeon v: kernel pcie: speed: 8 GT/s lanes: 8 ports: active: DVI-I-1 empty: DP-1
    bus-ID: 01:00.0 chip-ID: 1002:6611
  Device-2: Realtek RTL2838 DVB-T type: USB driver: dvb_usb_rtl28xxu,rtl2832_sdr bus-ID: 3-8:4
    chip-ID: 0bda:2838
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: ati,radeon
    unloaded: fbdev,modesetting,vesa gpu: radeon display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: DVI-0 mapped: DVI-I-1 model: Acer H233H res: 1920x1080 dpi: 96 diag: 585mm (23")
  OpenGL: renderer: OLAND ( LLVM 15.0.7 DRM 2.50 5.15.0-72-generic)
    v: 4.5 Mesa 22.2.5-0ubuntu0.1~22.04.3 direct render: Yes
Audio:
  Device-1: Intel 8 Series/C220 Series High Definition Audio vendor: Dell driver: snd_hda_intel
    v: kernel bus-ID: 00:1b.0 chip-ID: 8086:8c20
  Device-2: AMD Oland/Hainan/Cape Verde/Pitcairn HDMI Audio [Radeon HD 7000 Series] vendor: Dell
    driver: snd_hda_intel v: kernel pcie: speed: 8 GT/s lanes: 8 bus-ID: 01:00.1 chip-ID: 1002:aab0
  Sound Server-1: ALSA v: k5.15.0-72-generic running: yes
  Sound Server-2: JACK v: 1.9.20 running: no
  Sound Server-3: PulseAudio v: 15.99.1 running: yes
  Sound Server-4: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Ethernet I217-LM vendor: Dell driver: e1000e v: kernel port: f040
    bus-ID: 00:19.0 chip-ID: 8086:153a
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-1: virbr0 state: down mac: <filter>
Drives:
  Local Storage: total: 2.61 TiB used: 1.89 TiB (72.4%)
  ID-1: /dev/sda vendor: Western Digital model: WDS100T2B0A-00SM50 size: 931.51 GiB
    speed: 6.0 Gb/s serial: <filter>
  ID-2: /dev/sdb vendor: Samsung model: SSD 840 EVO 120GB size: 111.79 GiB speed: 6.0 Gb/s
    serial: <filter>
  ID-3: /dev/sdd type: USB vendor: Western Digital model: WD My Passport 25E1 size: 931.48 GiB
    serial: <filter>
  ID-4: /dev/sde type: USB vendor: Toshiba model: External USB HDD size: 698.64 GiB
    serial: <filter>
Partition:
  ID-1: / size: 98.44 GiB used: 35.13 GiB (35.7%) fs: ext4 dev: /dev/sdb1
  ID-2: /home size: 915.82 GiB used: 736.45 GiB (80.4%) fs: ext4 dev: /dev/sda1
Swap:
  ID-1: swap-1 type: partition size: 11.21 GiB used: 0 KiB (0.0%) priority: -2 dev: /dev/sdb2
Sensors:
  System Temperatures: cpu: 29.8 C mobo: 27.8 C gpu: radeon temp: 41.0 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: note: see --pkg apt: 4402
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/gambas-team-gambas3-jammy.list
    1: deb http: //ppa.launchpad.net/gambas-team/gambas3/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/jonaski-strawberry-jammy.list
    1: deb http: //ppa.launchpad.net/jonaski/strawberry/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/josm.list
    1: deb [signed-by=/usr/local/share/keyrings/josm-apt.gpg] https: //josm.openstreetmap.de/apt jammy universe
  Active apt repos in: /etc/apt/sources.list.d/krupkat-code-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/krupkat-code-jammy.gpg] https: //ppa.launchpadcontent.net/krupkat/code/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/microsoft-prod.list
    1: deb [arch=amd64,arm64,armhf] https: //packages.microsoft.com/ubuntu/22.04/prod jammy main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
[redacted
]  Active apt repos in: /etc/apt/sources.list.d/vscode.list
    1: deb [arch=amd64,arm64,armhf] http: //packages.microsoft.com/repos/code stable main
Info:
  Processes: 285 Uptime: 4h 6m Memory: 10.65 GiB used: 4.74 GiB (44.5%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.3.0 alt: 10/11/12 Client: Unknown python client inxi: 3.3.13

**Comment by jameslan** [comment]
Thanks for reporting.

It seems that you don't have the write privilege to the vscode installation.

The operation is to copy the built-in configuration files to backup files side by side. It failed because you can't write to that directory. However, even this step is fixed by writing the backup files to your personal directory. The following step to modify the original file will fail again for the same reason.

So I think you could either
- Run vscode with sudo, then execute this command within vscode
- Run a personal installation of vscode where you have full access to all files

**Comment by sjsepan3** [comment]
> * personal installation of vscode

As far as I can tell, most config files are in .config and .vscode or .vscode-oss (Codium) in my home directory. Except for this product.json.orig. I wonder why it is under /usr/share. 
I'll try the sudo approach, as I like the installation where it is.

UPDATE1:
`[sudo] password for *****:             
You are trying to start VSCodium as a super user which isn't recommended. If this was intended, please add the argument `--no-sandbox` and specify an alternate user data directory using the `--user-data-dir` argument.`

**Comment by jameslan** [comment]
No that's different.

The files you mentioned are for user preferences.

The setting for the url of the marketplace is part of the product vscode. So you need to be able to modify vscode as a product.

**Comment by sjsepan3** [comment]
OK, got it -- Thanks
